spring:
  redis:
    host: 10.23.109.38
    port: 6379
    password: 1234
    #    jedis:
    #      pool:
    #        max-active: 8
    #        max-idle: 8
    #        min-idle: 0
    #        max-wait: 200
    lettuce:
      pool:
        max-active: 8 # ????
        max-idle: 8 # ??????
        min-idle: 0 # ??????
        max-wait: 100 # ??????